name: Build and save PDF
on:
  push:
    branches:
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build PDF
      run: docker run --name latex --volume $PWD/paper.tex:/workdir/paper.tex mactavishediting/latex:latest make
    - name: Copy the DOCX
      run: docker cp latex:/workdir/paper.docx $PWD
    - name: Copy the PDF
      run: docker cp latex:/workdir/paper.pdf $PWD
    - name: Save the PDF and DOCX
      uses: actions/upload-artifact@v3
      with:
        name: paper
        path: |
          paper.pdf
          paper.docx
